// Same four styles as the front-end demo, ported to plain color/text
// config so both the browser preview and this server-side renderer draw
// from one source of truth. Add a new style by adding one entry here.

export const STYLES = {
  modern: {
    headerText: "TOGETHER WITH OUR FAMILIES",
    joinWord: "&",
    innerFrame: false,
    bgType: "linear",
    bgFrom: "#FBF7F1",
    bgTo: "#F6EFE4",
    borderColor: "#C9A15C",
    borderStyle: "single",
    headerColor: "#A9824A",
    nameColor: "#3B342B",
    ampColor: "#C9A15C",
    detailColor: "#6B6152",
    dateColor: "#3B342B",
    medallionColor: "#A9824A",
  },
  punjabi: {
    headerText: "SHUBH VIVAH",
    joinWord: "WEDS",
    innerFrame: true,
    bgType: "radial",
    bgFrom: "#7A1220",
    bgTo: "#4A0812",
    borderColor: "#D8AE5C",
    borderStyle: "double",
    headerColor: "#F6E3B4",
    nameColor: "#FCEFC4",
    ampColor: "#D8AE5C",
    detailColor: "#E9CE93",
    dateColor: "#FCEFC4",
    medallionColor: "#E9CE93",
  },
  south: {
    headerText: "SHUBHA VIVAHA",
    joinWord: "&",
    innerFrame: true,
    bgType: "linear",
    bgFrom: "#FBF3E1",
    bgTo: "#F5E7C6",
    borderColor: "#C9A15C",
    borderStyle: "double",
    headerColor: "#7A1F1F",
    nameColor: "#7A1F1F",
    ampColor: "#C9A15C",
    detailColor: "#6B4A1E",
    dateColor: "#5A3A1A",
    medallionColor: "#7A1F1F",
  },
  bengali: {
    headerText: "SHUBHO BIBAHO",
    joinWord: "&",
    innerFrame: true,
    bgType: "linear",
    bgFrom: "#FFFDF9",
    bgTo: "#FFF6F2",
    borderColor: "#B0202E",
    borderStyle: "double",
    headerColor: "#B0202E",
    nameColor: "#7A1220",
    ampColor: "#B0202E",
    detailColor: "#8A4A4A",
    dateColor: "#5A2020",
    medallionColor: "#B0202E",
  },
};
